name: JS
on: [push]
jobs:

  build:
    name: "Build (JS)"
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: 
        ./scripts/test-web

